[versions]
activityKtx = "1.9.0"
agp = "8.6.0"
androidGifDrawableVersion = "1.2.25"
appcompatVersion = "1.7.0"
cardview = "1.0.0"
composeBom = "2023.10.01"
comSquareupRetrofit2ConverterScalars4 = "2.9.0"
comSquareupOkhttp3Okhttp3 = "4.9.3"
constraintlayoutVersion = "2.2.0"
converterGson = "latest.version"
converterGsonVersion = "2.9.0"
coreKtxVersion = "1.12.0"
dotsindicator = "5.1.0"
dotsindicatorVersion = "4.3"
exifinterface = "1.4.0"
firebaseDatabaseKtxVersion = "20.2.1"
firebaseDatabaseVersion = "20.2.1"
glide = "5.0.5"
glideVersion = "4.16.0"
gradle = "8.1.2"
gson = "2.13.2"
gsonVersion = "2.10.1"
junitVersion = "1.1.6"
kotlin = "2.0.20"
androidGifDrawable = "1.2.29"
coreKtx = "1.13.1"
activity = "1.8.2"
appcompat = "1.6.1"
kotlinGradlePlugin = "1.9.10"
lifecycleCommonJava8 = "2.8.6"
material = "1.11.0"
constraintlayout = "2.1.4"
retrofit = "2.9.0"
savedstateKtx = "1.3.0"
sdpAndroid = "1.1.1"

# این سه خط رو حتماً داشته باشه (اینا باعث ارور بودن)
junit = "4.13.2"
junitExt = "1.1.5"
espresso = "3.5.1"
sdpAndroidVersion = "1.1.0"
googleServices = "4.4.4"
googleGmsGoogleServices = "4.4.4"
firebaseDatabase = "22.0.1"
firebaseDatabaseKtx = "22.0.1"

[libraries]
android-gif-drawable = { module = "pl.droidsonroids.gif:android-gif-drawable", version.ref = "androidGifDrawable" }
android-gif-drawable-v1225 = { module = "pl.droidsonroids.gif:android-gif-drawable", version.ref = "androidGifDrawableVersion" }
androidx-activity-ktx-v190 = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-appcompat-v170 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-constraintlayout-v220 = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-ktx-v1120 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
androidx-junit-v116 = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycleCommonJava8" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-savedstate-ktx = { module = "androidx.savedstate:savedstate-ktx", version.ref = "savedstateKtx" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
com-squareup-okhttp3-okhttp4 = { module = "com.squareup.okhttp3:okhttp", version.ref = "comSquareupOkhttp3Okhttp3" }
com-squareup-retrofit2-converter-scalars5 = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "comSquareupRetrofit2ConverterScalars4" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
converter-gson-v290 = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGsonVersion" }
dotsindicator = { module = "com.tbuonomo:dotsindicator", version.ref = "dotsindicator" }
dotsindicator-v43 = { module = "com.tbuonomo:dotsindicator", version.ref = "dotsindicatorVersion" }
firebase-database-ktx-v2021 = { module = "com.google.firebase:firebase-database-ktx", version.ref = "firebaseDatabaseKtxVersion" }
firebase-database-v2021 = { module = "com.google.firebase:firebase-database", version.ref = "firebaseDatabaseVersion" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-v4160 = { module = "com.github.bumptech.glide:glide", version.ref = "glideVersion" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
gson-v2101 = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material3 = { module = "androidx.compose.material3:material3" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpAndroid" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitExt" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
sdp-android-v110 = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpAndroidVersion" }
google-services = { group = "com.google.gms", name = "google-services", version.ref = "googleServices" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }
firebase-database-ktx = { group = "com.google.firebase", name = "firebase-database-ktx", version.ref = "firebaseDatabaseKtx" }
ui = { module = "androidx.compose.ui:ui" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }